name: mywallet
description: "MyWallet â€“ A smart, secure, and user-friendly app to send money with ease."
publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Optional: Uncomment below if you add Roboto fonts to assets/fonts/
  #
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500

  # Example for future assets (e.g., logo)
  #
  # assets:
  #   - assets/images/logo.png